name: IaC Pipeline

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

# Limit permissions to what is needed
permissions:
  contents: read

jobs:
  docker-build:
    uses: fxhibon/vps-iac/.github/workflows/docker-build-push.yml@master
    # You can pass inputs or secrets if needed:
    # with:
    #   environment: 'production'
    # secrets: inherit
